# Tensorflow 2.x

In [3]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.4.1'

## Constant
  * Defining a constant

In [4]:
tensor = tf.constant([[12,23,45],[45,76,34]])

In [5]:
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12, 23, 45],
       [45, 76, 34]], dtype=int32)>

In [8]:
tensor.shape

TensorShape([2, 3])

In [6]:
tf.print(tensor)

[[12 23 45]
 [45 76 34]]


In [9]:
tensor.numpy()

array([[12, 23, 45],
       [45, 76, 34]], dtype=int32)

In [10]:
numpy_array = np.array([[23,34],[45,67]])

In [12]:
tensor_from_numpy = tf.constant(numpy_array)

In [13]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23, 34],
       [45, 67]])>

In [16]:
tensor_from_numpy.numpy()

array([[23, 34],
       [45, 67]])

In [17]:
tf.print(tensor_from_numpy)

[[23 34]
 [45 67]]


**Variable**

  * Defining a Varibale

In [20]:
tensor_var = tf.Variable([[12,12],[34,23]])

In [21]:
tensor_var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[12, 12],
       [34, 23]], dtype=int32)>

In [22]:
tensor_var.numpy()

array([[12, 12],
       [34, 23]], dtype=int32)

In [23]:
tf.print(tensor_var)

[[12 12]
 [34 23]]


## Changing a Specific value is a tensorflow varibale

In [24]:
tensor_var[1,1].assign(50)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[12, 12],
       [34, 50]], dtype=int32)>

In [25]:
tensor_var[0,1].assign(50)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[12, 50],
       [34, 50]], dtype=int32)>

# Operations with tensorflow
 * Operations on tensorflow tensors

In [26]:
tensor = tf.constant([[1,2,3],[4,5,6]])
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

**Addition between tensor and scaler**

In [27]:
tensor + 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]], dtype=int32)>

**Multiplication betwwen tensor and scaler**

In [28]:
tensor * 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

**Using Numpy functions on tensors**

In [29]:
np.sum(tensor)

21

In [30]:
np.std(tensor)

1.707825127659933

In [31]:
np.sqrt(tensor)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [32]:
np.square(tensor)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [33]:
tensor_1 = tf.Variable([[23,34],[34,45]])
tensor_1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[23, 34],
       [34, 45]], dtype=int32)>

In [34]:
tensor_2 = tf.Variable([[12,23],[34,34]])
tensor_2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[12, 23],
       [34, 34]], dtype=int32)>

# tensorflow Strings
  * Defining Strings

In [39]:
tf_string = tf.constant('tensorflow')
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'tensorflow'>

### Strings Operations on tensorflow strings

In [40]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

## Convert string into tensor numbr

In [44]:
tf.strings.unicode_decode(tf_string, 'UTF8')

# UTF8 is a format

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([116, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

### Storing arrays of stings

In [45]:
tf_string_array = tf.constant(['tensorflow', 'Deep Learning', 'Neural Network'])

In [55]:
# Iteration through tensorflow string array

for string in tf_string_array:
  print(string)
  code = tf.strings.unicode_decode(string, 'UTF8')
  tf.print('String Decoded : ' + str(code))
  


tf.Tensor(b'tensorflow', shape=(), dtype=string)
String Decoded : tf.Tensor([116 101 110 115 111 114 102 108 111 119], shape=(10,), dtype=int32)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
String Decoded : tf.Tensor([ 68 101 101 112  32  76 101  97 114 110 105 110 103], shape=(13,), dtype=int32)
tf.Tensor(b'Neural Network', shape=(), dtype=string)
String Decoded : tf.Tensor([ 78 101 117 114  97 108  32  78 101 116 119 111 114 107], shape=(14,), dtype=int32)
