# Tensorflow 1.X

Installing tensorflow 1.X

Avoid  `pip install` use magicline in select tensorflow version

In [2]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
import tensorflow as tf

In [4]:
tf.__version__

'1.15.2'

## Constant
**Defining Constant**

In [6]:
tensor = tf.constant([[23,4], [5,5]])

In [7]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [11]:
constnt = tf.constant([[23,45,34], [34,23,45]])

In [12]:
constnt

<tf.Tensor 'Const_1:0' shape=(2, 3) dtype=int32>

In [14]:
constnt = tf.constant([[23,23,344],[34,45,76],[45,56,45]])

In [15]:
constnt

<tf.Tensor 'Const_2:0' shape=(3, 3) dtype=int32>

**Now to print the constant values in tensorflow 1.x we will initialize session and through eval() function wwe can print values**

**Getting values of Constant**

In [19]:
session = tf.Session()

In [35]:
session.run(tf.global_variables_initializer())

In [36]:
tensor_values = session.run(tensor)

In [37]:
tensor_values

array([[23,  4],
       [ 5,  5]], dtype=int32)

In [38]:
tensor_values = session.run(constnt)

In [39]:
tensor_values

array([[ 23,  23, 344],
       [ 34,  45,  76],
       [ 45,  56,  45]], dtype=int32)

## Variables

**Defining a variable**

In [26]:
varibale = tf.Variable([[12,34],[23,45]])

In [27]:
varibale

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [30]:
session.run(tf.global_variables_initializer())

In [31]:
var_value = session.run(varibale)

In [32]:
var_value

array([[12, 34],
       [23, 45]], dtype=int32)

In [41]:
# OR

varibale.eval(session)

array([[12, 34],
       [23, 45]], dtype=int32)

---

# Tensorflow 2.X

---

In [2]:
%tensorflow_version 2.x

In [4]:
tf.__version__

NameError: ignored